#!/usr/bin/env python

""" TODAY: We write history (into files) """

from prompt_toolkit.shortcuts import PromptSession
from prompt_toolkit.history import FileHistory


def main():
    history = FileHistory(".mee_history")
    session = PromptSession(" >>> ", history=history)
    while True:
        try:
            stmt = session.prompt()
            print(f"You said: {stmt}")
        except EOFError:
            break


if __name__ == "__main__":
    main()
