#!/usr/bin/env python

""" Rainbow SQL """

from pygments.lexers.sql import SqlLexer

from prompt_toolkit.lexers import PygmentsLexer
from prompt_toolkit.shortcuts import PromptSession
from prompt_toolkit.history import FileHistory


def main():
    history = FileHistory(".mee_history")
    session = PromptSession(
        " >>> ",
        history=history,
        lexer=PygmentsLexer(SqlLexer),
    )
    while True:
        try:
            stmt = session.prompt()
            print(f"You said: {stmt}")
        except EOFError:
            break


if __name__ == "__main__":
    main()
